a71: Rename NFC HAL to avoid conflicts
* Fixes:
hardware/nxp/nfc/pn8x/1.2/NxpNfcService.cpp:25:10: fatal error: 'NxpNfc.h' file not found
   25 | #include "NxpNfc.h"

Change-Id: I5de90e2fe639cdfc2bdd8a43b29d0e4fa4bd31ea